import * as React from 'react'
import Head from 'next/head'
import Hero from '@components/components/Hero'
import Contact from '@components/components/Contact'
import Tech from '@components/components/Projects'
import Slides from '@components/components/Slides'
import PageBg from '@components/components/PageBg'
import GridStripSection from '@components/components/GridStripSection'
import useTheme from '@components/hooks/useTheme'

export default function FunFunFun() {
  const colorTheme = useTheme()

  return (
    <>
      <Head>
        <title>Patrick Lake | Fun Fun Fun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="bg-dark"
        id="page-wrapper"
        style={{ '--color': colorTheme?.dark } as React.CSSProperties}
      >
        <PageBg>
          <Hero hasGridAnimation />
          <div className="mnt-xxxl">
            <GridStripSection />
          </div>
          <Tech project={'node.js'} />
          <div className="mnt-xxxl">
            <GridStripSection />
          </div>
          <Tech project={'GSAP.js'} />
          {/* <Slides
            slides={[
              { text: 'Do', className: 'h3' },
              { text: 'The', className: 'h2' },
              { text: 'Dew', className: 'h1' },
            ]}
            bgColor="dark"
          /> */}
          {/* <div style={{ minHeight: '100vh' }}>
            {[...Array(12)].map((_, i) => (
              <div key={i} className={`spacer-${i}`} />
            ))}
          </div> */}
          <Contact />
        </PageBg>
      </main>
    </>
  )
}
