import * as React from 'react'
import Head from 'next/head'
import Hero from '@components/components/Hero'
import Contact from '@components/components/Contact'
import Tech from '@components/components/Tech'
import PageBg from '@components/components/PageBg'
import GridStripSection from '@components/components/GridStripSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Patrick Lake | NodeJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <main className="position-relative z-1">
          {/* <PageBg> */}
          <Hero />
          <div className="mnt-xxxl">
            <GridStripSection />
          </div>
          <Tech project={'node.js'} />
          <div className="mnt-xxxl">
            <GridStripSection />
          </div>
          <Tech project={'GSAP.js'} />
          <Contact />
          {/* </PageBg> */}
        </main>
      </>
    </>
  )
}
